# Generated by Django 6.0.4 on 2026-05-01 16:11

import identity.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_add_db_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[identity.validators.validate_avatar_extension, identity.validators.validate_avatar_size, identity.validators.validate_avatar_content], verbose_name='Profil Fotoğrafı'),
        ),
    ]
