# Generated by Django 6.0.4 on 2026-05-03 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_department_manager'),
        ('identity', '0005_sync_admin_is_staff'),
        ('tickets', '0006_remove_ticket_attachment_ticketattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('TICKET', 'Bilet'), ('USER', 'Kullanıcı'), ('DEPARTMENT', 'Departman'), ('CATEGORY', 'Kategori'), ('AUTH', 'Kimlik Doğrulama'), ('OTHER', 'Diğer')], default='OTHER', max_length=20, verbose_name='Kategori')),
                ('action', models.CharField(max_length=300, verbose_name='Aksiyon')),
                ('target_repr', models.CharField(blank=True, default='', max_length=200, verbose_name='Hedef')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL, verbose_name='İşlemi Yapan')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='departments.department', verbose_name='İlgili Departman')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='tickets.ticket', verbose_name='İlgili Bilet')),
            ],
            options={
                'verbose_name': 'Geçmiş Kaydı',
                'verbose_name_plural': 'Geçmiş Kayıtları',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='identity_au_created_f24fc0_idx'), models.Index(fields=['category', '-created_at'], name='identity_au_categor_8e0188_idx'), models.Index(fields=['actor', '-created_at'], name='identity_au_actor_i_a477af_idx')],
            },
        ),
    ]
