# Generated by Django 6.0.4 on 2026-05-04 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_tag_ticket_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcomment',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='comment_attachments/%Y/%m/', verbose_name='Dosya Eki'),
        ),
        migrations.AlterField(
            model_name='ticketcomment',
            name='content',
            field=models.TextField(blank=True, max_length=2000, verbose_name='Yorum'),
        ),
    ]
