# Generated by Django 6.0.4 on 2026-05-04 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_add_comment_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='resolution_confirmed',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Çözüm Onayı'),
        ),
    ]
