# Generated by Django 6.0.4 on 2026-05-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_lifecycle_states'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Açık'), ('IN_PROGRESS', 'İşlemde'), ('RESOLVED', 'Çözüldü'), ('CLOSED', 'Kapandı'), ('ESCALATED', 'Eskalasyon')], default='OPEN', max_length=20, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='tickethistory',
            name='action_type',
            field=models.CharField(choices=[('CREATED', 'Bilet oluşturuldu'), ('TAKEN', 'Bilet üstlenildi'), ('ASSIGNED', 'Personel atandı'), ('UNASSIGNED', 'Atama kaldırıldı'), ('RESOLVED', 'Bilet çözüldü olarak işaretlendi'), ('CLOSED', 'Bilet kapatıldı'), ('AUTO_CLOSED', 'Bilet otomatik kapatıldı'), ('REOPENED', 'Bilet yeniden açıldı'), ('ESCALATED', 'Bilet eskalasyona alındı'), ('TRANSFERRED', 'Bilet transfer edildi'), ('UPDATED', 'Bilet güncellendi'), ('RESOLUTION_CONFIRMED', 'Çözüm onaylandı'), ('RESOLUTION_REJECTED', 'Çözüm reddedildi'), ('CSAT_RATED', 'Memnuniyet puanlandı'), ('OTHER', 'Diğer')], default='OTHER', max_length=30, verbose_name='Aksiyon Tipi'),
        ),
    ]
