# Generated by Django 6.0.4 on 2026-05-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_alter_ticket_status_alter_tickethistory_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='sla_warning_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='SLA Uyarısı Gönderildi'),
        ),
    ]
