# Generated by Django 6.0.4 on 2026-06-13 02:13

from django.db import migrations, models


# Mevcut biletlerin sla_due_at değerini çalışma saatleri bazlı geriye dönük doldur.
def backfill_sla_due_at(apps, schema_editor):
    from tickets.models import SLA_HOURS, add_business_hours, Priority
    Ticket = apps.get_model('tickets', 'Ticket')
    to_update = []
    for t in Ticket.objects.all().only('id', 'created_at', 'priority'):
        if not t.created_at:
            continue
        hours = SLA_HOURS.get(t.priority, SLA_HOURS[Priority.NORMAL])
        t.sla_due_at = add_business_hours(t.created_at, hours)
        to_update.append(t)
    Ticket.objects.bulk_update(to_update, ['sla_due_at'], batch_size=500)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_ticket_sla_warning_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='sla_due_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='SLA Hedef Tarihi'),
        ),
        migrations.RunPython(backfill_sla_due_at, noop_reverse),
    ]
