# Generated by Django 6.0.4 on 2026-09-29 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0004_department_auto_assign_enabled_and_more'),
        ('tickets', '0014_ticket_sla_due_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CannedResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Başlık')),
                ('body', models.TextField(max_length=2000, verbose_name='Metin')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='Kullanım Sayısı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Hazır Yanıt',
                'verbose_name_plural': 'Hazır Yanıtlar',
                'ordering': ['department__name', 'title'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='first_response_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='İlk Yanıt Tarihi'),
        ),
        migrations.AddField(
            model_name='ticketcomment',
            name='is_internal',
            field=models.BooleanField(default=False, help_text='Yalnızca ilgili departmanın personeli ve Admin görür; talep sahibine gösterilmez.', verbose_name='Dahili Not'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['first_response_at'], name='ticket_first_resp_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketcomment',
            index=models.Index(fields=['ticket', 'is_internal'], name='comment_ticket_internal_idx'),
        ),
        migrations.AddField(
            model_name='cannedresponse',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Yalnızca bilgi amaçlı daraltma; zorunlu değildir.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canned_responses', to='departments.category', verbose_name='Kategori'),
        ),
        migrations.AddField(
            model_name='cannedresponse',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canned_responses', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan'),
        ),
        migrations.AddField(
            model_name='cannedresponse',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Boş bırakılırsa tüm departmanlar kullanabilir.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='canned_responses', to='departments.department', verbose_name='Departman'),
        ),
        migrations.AddConstraint(
            model_name='cannedresponse',
            constraint=models.UniqueConstraint(condition=models.Q(('department__isnull', False)), fields=('department', 'title'), name='cannedresponse_dept_title_uniq'),
        ),
        migrations.AddConstraint(
            model_name='cannedresponse',
            constraint=models.UniqueConstraint(condition=models.Q(('department__isnull', True)), fields=('title',), name='cannedresponse_global_title_uniq'),
        ),
    ]
