# Generated by Django 6.0.4 on 2026-05-03 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_add_db_indexes'),
        ('tickets', '0006_remove_ticket_attachment_ticketattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='tickets.ticket', verbose_name='İlgili Bilet'),
        ),
    ]
